// Return a random boolean with true probablility percentage provided
getBoolean = (prob) => Math.random() < prob / 100.0;

// Return a random integer between min and max-1 (inclusive)
getInteger = (min, max) => Math.trunc(Math.random() * (max - min) + min);

// Return HEAT, COOL, and OFF
getHVACMode = () => {
  const n = Math.trunc(Math.random() * 3);
  switch (n) {
    case 0:
      return "HEAT";
    case 1:
      return "COOL";
    case 2:
      return "OFF";
    default:
      return "UNKNOWN";
  }
};

exports.sensorModel = () => [
  {
    id: "UXBTUSGC",
    groupId: "water",
    groupName: "Water",
    description: "Water meter flow rate",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(0, 15),
  },
  {
    id: "OYXIUPTT",
    groupId: "water",
    groupName: "Water",
    description: "Water heater temperature",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(60, 200),
  },
  {
    id: "PHNLXUDA",
    groupId: "water",
    groupName: "Water",
    description: "Floor water sensor - bathroom 1",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "UNASUCCE",
    groupId: "water",
    groupName: "Water",
    description: "Floor water sensor - bathroom 2",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "THCTTGTI",
    groupId: "water",
    groupName: "Water",
    description: "Floor water sensor - bathroom 3",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "QAJJYCYK",
    description: "Front door",
    groupId: "door",
    groupName: "Doors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(10),
  },
  {
    id: "SSYWZECQ",
    description: "Garage door",
    groupId: "door",
    groupName: "Doors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(20),
  },
  {
    id: "JVRPFATJ",
    description: "Side door",
    groupId: "door",
    groupName: "Doors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(10),
  },
  {
    id: "JVRPFATJ",
    description: "Family room window 1",
    groupId: "window",
    groupName: "Windows",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(10),
  },
  {
    id: "EHXBVCCW",
    description: "Family room window 2",
    groupId: "window",
    groupName: "Windows",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(10),
  },
  {
    id: "CKYKPWUU",
    description: "Bedroom 1",
    groupId: "window",
    groupName: "Windows",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "YJBORCPH",
    description: "Bedroom 2",
    groupId: "window",
    groupName: "Windows",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "DYWBJAXG",
    description: "Bedroom 3",
    groupId: "window",
    groupName: "Windows",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "LNMLWUPB",
    description: "Bathroom 1",
    groupId: "window",
    groupName: "Windows",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "FZIGXKHW",
    description: "Bathroom 2",
    groupId: "window",
    groupName: "Windows",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "LXDJXEDG",
    description: "Window breakage",
    groupId: "window",
    groupName: "Windows",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "LXDJXEDG",
    description: "Motion sensor 1",
    groupId: "motion",
    groupName: "Motion sensors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "KIUSJJZK",
    description: "Motion sensor 2",
    groupId: "motion",
    groupName: "Motion sensors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "SKBMUXKI",
    description: "Motion sensor 3",
    groupId: "motion",
    groupName: "Motion sensors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "BFRMBWJP",
    description: "HVAC status",
    groupId: "thermostat",
    groupName: "Thermostats",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "FZNLBSLA",
    description: "HVAC mode",
    groupId: "thermostat",
    groupName: "Thermostats",
    fault: getBoolean(1),
    dataType: "string",
    value: getHVACMode(),
  },
  {
    id: "FZNLBSLA",
    description: "HVAC blower",
    groupId: "thermostat",
    groupName: "Thermostats",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(50),
  },
  {
    id: "RHPSDQLV",
    description: "Indoor temperature",
    groupId: "thermostat",
    groupName: "Thermostats",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(50, 100),
  },
  {
    id: "FULXXMJG",
    description: "Outdoor temperature",
    groupId: "thermostat",
    groupName: "Thermostats",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(-30, 130),
  },
  {
    id: "GGSXFEAF",
    description: "Refrigerator temperature",
    groupId: "appliance",
    groupName: "Appliance sensors",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(-5, 60),
  },
  {
    id: "JBZTAMVO",
    description: "Ice maker filter",
    groupId: "appliance",
    groupName: "Appliance sensors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(5),
  },
  {
    id: "GFTXIIDL",
    description: "Freezer temperature",
    groupId: "appliance",
    groupName: "Appliance sensors",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(-20, 40),
  },
  {
    id: "QPRHXJJZ",
    description: "Stove status",
    groupId: "appliance",
    groupName: "Appliance sensors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(15),
  },
  {
    id: "LAXOWEXA",
    description: "Dishwasher status",
    groupId: "appliance",
    groupName: "Appliance sensors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(15),
  },
  {
    id: "TKCMVEMM",
    description: "Oven status",
    groupId: "appliance",
    groupName: "Appliance sensors",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(15),
  },
  {
    id: "QIFRIJEK",
    description: "Upper oven temperature",
    groupId: "appliance",
    groupName: "Appliance sensors",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(60, 600),
  },
  {
    id: "EWDGTEVP",
    description: "Lower oven temperature",
    groupId: "appliance",
    groupName: "Appliance sensors",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(60, 600),
  },
  {
    id: "AFKKNDHE",
    description: "Solar system status",
    groupId: "electric",
    groupName: "Electric systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(97),
  },
  {
    id: "JMYRVONP",
    description: "Solar system fault",
    groupId: "electric",
    groupName: "Electric systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(2),
  },
  {
    id: "GITNOOWU",
    description: "Solar system production",
    groupId: "electric",
    groupName: "Electric systems",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(0, 20),
  },
  {
    id: "KFLRUEDD",
    description: "Utility power",
    groupId: "electric",
    groupName: "Electric systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(99),
  },
  {
    id: "AOEDGIZY",
    description: "Utility consumption",
    groupId: "electric",
    groupName: "Electric systems",
    fault: getBoolean(1),
    dataType: "number",
    value: getInteger(0, 30),
  },
  {
    id: "OPGBTMAN",
    description: "Bedroom 1 smoke sensor",
    groupId: "safety",
    groupName: "Safety systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(1),
  },
  {
    id: "GRYZVADE",
    description: "Bedroom 2 smoke sensor",
    groupId: "safety",
    groupName: "Safety systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(1),
  },
  {
    id: "MUDUSYSZ",
    description: "Bedroom 3 smoke sensor",
    groupId: "safety",
    groupName: "Safety systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(1),
  },
  {
    id: "YNFCVHZO",
    description: "Master bedroom smoke sensor",
    groupId: "safety",
    groupName: "Safety systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(1),
  },
  {
    id: "KXHLINHS",
    description: "Hallway smoke sensor",
    groupId: "safety",
    groupName: "Safety systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(1),
  },
  {
    id: "YRKXEZRK",
    description: "Garage heat sensor",
    groupId: "safety",
    groupName: "Safety systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(1),
  },
  {
    id: "HRZQWBKN",
    description: "Kitchen heat sensor",
    groupId: "safety",
    groupName: "Safety systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(1),
  },
  {
    id: "HEENNMZU",
    description: "Carbon Monoxide sensor",
    groupId: "safety",
    groupName: "Safety systems",
    fault: getBoolean(1),
    dataType: "boolean",
    value: getBoolean(1),
  },
];
